### ISSUE TITLE
Implement word wrapping

### ISSUE THREAD

**Issue by haroldo-ok** [haroldo-ok/choice4genesis#22]

**Comment by zartan9** [comment]
cant wait :) will the text be automatically justified/hypenated too? Im chipping away at adding text 👍

**Comment by haroldo-ok** [comment]
It may be a good idea to add the capability of setting alignment/justification; not sure if it would be possible to add hyphenation, but that could be looked into.

**Comment by zartan9** [comment]
works! But now pictures not showing? 

rc/generated_scripts.c: In function 'VS_startup':
src/generated_scripts.c:14:6: warning: variable 'VL_localInt' set but not used [-Wunused-but-set-variable]
  int VL_localInt = 2;
      ^~~~~~~~~~~
src/generated_scripts.c: In function 'VS_gen19a':
src/generated_scripts.c:190:19: error: 'g19v1_png' undeclared (first use in this function)
    VN_background(&g19v1_png);
                   ^~~~~~~~~
src/generated_scripts.c:190:19: note: each undeclared identifier is reported only once for each function it appears in
make: *** [out/src/generated_scripts.o] Error 1
rm res/sprite.rs
SGDK compiler exited with code 2

**Comment by haroldo-ok** [comment]
From this line:
```
src/generated_scripts.c:190:19: error: 'g19v1_png' undeclared (first use in this function)
VN_background(&g19v1_png);
```
It looks like it is not finding "g19v1.png"; please try checking if the name given on the script file is the same as in the image file.

**Comment by zartan9** [comment]
It looks the same and it's a png hmm.

Sent from the all new AOL app for Android 
 
  On Wed, Oct 26, 2022 at 5:03 AM, Haroldo de Oliveira ***@***.***> wrote:   


From this line:
src/generated_scripts.c:190:19: error: 'g19v1_png' undeclared (first use in this function)
VN_background(&g19v1_png);

It looks like it is not finding "g19v1.png"; please try checking if the name given on the script file is the same as in the image file.

**Comment by haroldo-ok** [comment]
I see... could you please attach the project so that the bug can be reproduced?

**Comment by zartan9** [comment]
ok  i added it on github its a big file thank you


-----Original Message-----
