### ISSUE TITLE
Background images are being shown incorrectly

### ISSUE THREAD

**Issue by haroldo-ok** [haroldo-ok/choice4genesis#89]
>![momoutake](https://user-images.githubusercontent.com/74879950/207380447-9a03d0e8-8ac6-4884-8a18-af9daf58f625.png)
>sure! this can help narrow down the automatic image process.. the woman image is the one scrambling.  the one with
pencil on guy is working (the pencil color doesnt show up but thats ok for now...)
>![pencil](https://user-images.githubusercontent.com/74879950/207380674-11a6c730-b3cd-4acb-a2b1-97b0be100aac.png)
> Thanks
> _Originally posted by @zartan9 in https://github.com/haroldo-ok/choice4genesis/issues/66#issuecomment-1348872185_

Okay, thanks; it seems that, indeed, that image is being displayed incorrectly, no matter how many ways one tries to convert it. I'll have to take a look at this one later.

[bug.zip](https://github.com/haroldo-ok/choice4genesis/files/10222221/bug.zip)

**Comment by haroldo-ok** [comment]
Starting to look at the bug.
Working branch: https://github.com/haroldo-ok/choice4genesis/tree/fix-background-image-bug

**Comment by haroldo-ok** [comment]
It does not seem to be a tileMap problem; if the tilemap part gets commented out, the bug still happens. `VDP_loadTileSet()` does return null, though, indicating that it is running out of memory.

```c
void VN_showImage(const Image *image, VDPPlane plane, u16 palNum, u16 x, u16 y) {
	VDP_loadTileSet(image->tileset, imageInfo.tileNumber, DMA);

	TileMap *tmap = unpackTileMap(image->tilemap, NULL);
	VDP_setTileMapEx(plane, tmap, TILE_ATTR_FULL(palNum, FALSE, FALSE, FALSE, imageInfo.tileNumber), 
		x, y,  0, 0, tmap->w, tmap->h, CPU);
	MEM_free(tmap);

	VDP_setPalette(palNum, (u16*)image->palette->data);
	imageInfo.tileNumber += image->tileset->numTile;
}
```

Tested various permutations of the code, with various configurations, even going as far as removing compression; the problem persists.

**Comment by zartan9** [comment]
ok keep me posted im sure youll get it!! Im working on the text in the meantime! thanks!
    On Sunday, January 8, 2023 at 05:49:53 PM EST, Haroldo de Oliveira Pinheiro ***@***.***> wrote:  
 
 


It does not seem to be a tileMap problem; if the tilemap part gets commented out, the bug still happens. VDP_loadTileSet() does return null, though, indicating that it is running out of memory.
void VN_showImage(const Image *image, VDPPlane plane, u16 palNum, u16 x, u16 y) {
	VDP_loadTileSet(image->tileset, imageInfo.tileNumber, DMA);

	TileMap *tmap = unpackTileMap(image->tilemap, NULL);
	VDP_setTileMapEx(plane, tmap, TILE_ATTR_FULL(palNum, FALSE, FALSE, FALSE, imageInfo.tileNumber), 
		x, y,  0, 0, tmap->w, tmap->h, CPU);
	MEM_free(tmap);

	VDP_setPalette(palNum, (u16*)image->palette->data);
	imageInfo.tileNumber += image->tileset->numTile;
}
Tested various permutations of the code, with various configurations, even going as far as removing compression; the problem persists.

**Comment by zartan9** [comment]
i knew you could do it! it works!
    On Sunday, January 8, 2023 at 05:49:53 PM EST, Haroldo de Oliveira Pinheiro ***@***.***> wrote:  
 
 


It does not seem to be a tileMap problem; if the tilemap part gets commented out, the bug still happens. VDP_loadTileSet() does return null, though, indicating that it is running out of memory.
void VN_showImage(const Image *image, VDPPlane plane, u16 palNum, u16 x, u16 y) {
	VDP_loadTileSet(image->tileset, imageInfo.tileNumber, DMA);

	TileMap *tmap = unpackTileMap(image->tilemap, NULL);
	VDP_setTileMapEx(plane, tmap, TILE_ATTR_FULL(palNum, FALSE, FALSE, FALSE, imageInfo.tileNumber), 
		x, y,  0, 0, tmap->w, tmap->h, CPU);
	MEM_free(tmap);

	VDP_setPalette(palNum, (u16*)image->palette->data);
	imageInfo.tileNumber += image->tileset->numTile;
}
Tested various permutations of the code, with various configurations, even going as far as removing compression; the problem persists.

**Comment by haroldo-ok** [comment]
Thanks!
